name: Konan cache
description: Cache for Kotlin/Native compiler
inputs:
  job-type:
    description: 'Type of the job requesting the cache (e.g., publish, test, etc.)'
    required: true
runs:
  using: "composite"
  steps:
    - name: Cache
      uses: actions/cache@v5
      with:
        path: ~/.konan
        key: konan|${{ runner.os }}|${{ runner.arch }}|${{ inputs.job-type }}|${{ hashFiles('**/*.gradle*') }}|${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}|${{ hashFiles('**/gradle/libs.versions.toml') }}
        restore-keys: |
          konan|${{ runner.os }}|${{ runner.arch }}|${{ inputs.job-type }}
          konan|${{ runner.os }}|${{ runner.arch }}
          konan|${{ runner.os }}
