# Command completion for caupain
# Generated by Clikt

## Options for caupain
complete -c caupain -s i -l version-catalog -r -F -d 'Version catalog path. Use multiple times to use multiple version catalogs'
complete -c caupain -l gradle-wrapper-properties -r -F -d 'Gradle wrapper properties path'
complete -c caupain -s e -l excluded -r -d 'Excluded keys'
complete -c caupain -s c -l config -r -F -d 'Configuration file'
complete -c caupain -l policy-plugin-dir -r -F -d 'Custom policies plugin dir'
complete -c caupain -s p -l policy -r -d 'Update policy'
complete -c caupain -l list-policies -d 'List available policies'
complete -c caupain -s t -l output-type -r -fa "console html markdown json" -d 'Output type'
complete -c caupain -s o -l output -r -F -d 'Report output path'
complete -c caupain -l show-version-references -d 'Show versions references update summary in the report'
complete -c caupain -l cache-dir -r -F -d 'Cache directory. This is not used if --no-cache is set'
complete -c caupain -l no--cache -d 'Disable HTTP cache'
complete -c caupain -s q -l quiet -d 'Suppress all output'
complete -c caupain -s v -l verbose -d 'Verbose output'
complete -c caupain -s d -l debug -d 'Debug output'
complete -c caupain -l debug-http-calls -d 'Enable debugging for HTTP calls'
complete -c caupain -l version -d 'Show the version and exit'
complete -c caupain -s h -l help -d 'Show this message and exit'

